[buil]
[build]
cmds = [
"npm install"
"npm rebuild"
"npm run build"
]
[start]
cmd = "npm start"
OEF
cat > .nixpacks.toml << 'EOF'
[build]
cmds = [
  "npm install",
  "npm rebuild",
  "npm run build"
]

[start]
cmd = "npm start"
